### ISSUE TITLE
Downloads 20 images

### ISSUE THREAD

**Issue by StewPoll** [gideonn/Insta-Gallery-Downloader#4]
Only downloads 20 images for me

**Comment by s3dev** [comment]
Brilliant bot mate, nicely done.  Any solution to the issue TetraEtc pointed out?  It's only downloading the 20 most recent images.  Is there any way around this that you know of?  Cheers mate, thank you!

**Comment by hrxn** [comment]
Is this still happening? I can't test it with my account right now, don't even have close to 20 images..

Maybe they changed their API just recently?
@gideonn can you maybe confirm this?

**Comment by g1deon** [comment]
Instagram has recently made changes to how their APIs behave for sandbox applications. I'll see if I can get this fixed. I'll be updating the readMe section once done.

**Comment by hrxn** [comment]
Thanks a lot for looking into this! :+1:

**Comment by gideonn** [comment]
@Hrxn : Just get a new token generated, the script should work fine.

The new API only supports interacting with the users that are in sandbox allowed list. By default, its only you. 
Either way, you should be able to download all your images using the same code. I tried and tested it with new token and it works fine.

**Comment by hrxn** [comment]
Okay, thank you again!
