### ISSUE TITLE
Feature Request: Download images of people you follow, put in their own folder

### ISSUE THREAD

**Issue by StewPoll** [gideonn/Insta-Gallery-Downloader#5]

**Comment by StewPoll** [comment]
Get people you follow with the /users/self/follows endpoint

**Comment by gideonn** [comment]
I don't think many users would want to do that.
You can fork my code and use the endpoint, if you want to do it.

**Comment by hrxn** [comment]
Well, this endpoint does not seem to work anymore.

Do you maybe know what's going on there?

**Comment by StewPoll** [comment]
Instagram did change their API. This may no longer work. I'm not Abhishek
though

**Comment by hrxn** [comment]
Yes, I'm aware..
Well, too bad.
