### ISSUE TITLE
Pretty sure this is not the appropriate place to ask but..

### ISSUE THREAD

**Issue by thejcode24** [gideonn/Insta-Gallery-Downloader#6]
Hi I am a beginner programmer and found your post on reddit, and I thought it was perfect for someone like me to study because it seems "easier" (not that it's easy at all) compared to other github projects I found. I am studying regex and was wondering if you can guide me through your regex part of code. Thanks in advance.

**Comment by gideonn** [comment]
Hi @thejcode24, this place is for opening issues in the script/program.
Please mail me anything that you want to understand, I'll be happy to help you out!

Closing the issue.
